[versions]
lombok = "1.18.32"
spring-boot = "3.4.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }